### PR TITLE
Issue 939: Error with setInternalState and JDK12 "java.lang.NoSuchFieldException: modifiers

### LINKED ISSUE #939: Error with setInternalState and JDK12 "java.lang.NoSuchFieldException: modifiers"
What steps will reproduce the problem?
Use WhiteBox#setInternalState with JDK12 

What is the expected output?
setInternalState does not throw exception

What do you see instead?
```
java.lang.RuntimeException: Internal error: Failed to find the "modifiers" field in method setInternalState.
	at org.powermock.reflect.internal.WhiteboxImpl.sedModifiersToField(WhiteboxImpl.java:2354)
	at org.powermock.reflect.internal.WhiteboxImpl.removeFinalModifierIfPresent(WhiteboxImpl.java:2318)
	at org.powermock.reflect.internal.WhiteboxImpl.setField(WhiteboxImpl.java:2304)
	at org.powermock.reflect.internal.WhiteboxImpl.setInternalState(WhiteboxImpl.java:304)
	at org.powermock.reflect.internal.WhiteboxImpl.setInternalState(WhiteboxImpl.java:317)
	at org.powermock.reflect.Whitebox.setInternalState(Whitebox.java:190)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:61)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```

What version of the product are you using? 
2.0.0.Beta5

### PR DESCRIPTION
**Pull request by eolivelli**
Add a catch clause in order to workaround a problem with PowerMockRunner and JDK12

Signed-off-by: Enrico Olivelli - Diennea <enrico.olivelli@diennea.com>

Fixes #939

### CODE REVIEW

**Comment by eolivelli** [comment]
@thekingnothing can you please  take a look ? this is quite blocker for testing of projects of JDK12.

**Comment by eolivelli** [comment]
@ijuma do you think this change will be useful in your case ?

File: powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java [hunk 1]
```diff
@@ -58,7 +58,16 @@ public void run(RunNotifier notifier) {
         try {
             super.run(notifier);
         } finally {
-            Whitebox.setInternalState(description, "fAnnotations", new Annotation[]{});
+            try {
+               Whitebox.setInternalState(description, "fAnnotations", new Annotation[]{});
```
Comment (Tibor17) [inline powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java:62]: Why the old code made such a drastic operation?
@thekingnothing Is it really needed because it looks like a workaround of something?

Comment (thekingn0thing) [reply powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java:62]: @Tibor17 it's a "dirty hack" to fix out memory issue. However, I don't see a lot of benefits as annotation does not consume a lot of memory and does not store any state or link to a heavy object.

**Comment by eolivelli** [comment]
Great!

I thank you.
Hoping to see soon a new release in Maven central

**Comment by thekingn0thing** [comment]
Thank you. In theory, the release should be in Maven central in next few minutes, however, sync between bintray and maven central usually fails. So the release will be in next few hours.

File: powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java (hunk 1 above)
Comment (Tibor17) [reply powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java:62]: @thekingnothing 
The performance issues are understandable, but I was asking for the purpose why annotations had to be removed from `Description` after Runners execution. Nobody reads them anyway after the runner has finished.

**Comment by Tibor17** [comment]
@thekingnothing 
I have a question to Javasist version. The Maven Enforcer Plugin found that Javasist is compiled with Java 1.8. Is this required in PowerMock? Can we use older version compliant with Java 1.7?

File: powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java (hunk 1 above)
Comment (thekingn0thing) [reply powermock-modules/powermock-module-junit4/src/main/java/org/powermock/modules/junit4/PowerMockRunner.java:62]: Here I cannot help, as this code was introduced 7 years ago and I'm supporting PowerMock only for 3 years. I cannot say the real reason why it was done in such a way.

**Comment by thekingn0thing** [comment]
@Tibor17 a Javasist version was upgraded as part of the #952 pull request to add supporting JDK 11.  PowerMock does not depend directly on any new feature of the latest Javasist, so it works fine with previous versions except that previous Javasist's versions could not work with JDK 10/11.
