### PR TITLE
Fix #781: Call mocked equals static method instead of real.

### LINKED ISSUE #781: Real equals static methods are called instead of mocked
Real equals static methods are called instead of mocked for equals static methods that are called from a stub. 

```
public class SpyObject {
    public boolean callEquals() {
        return EqualsStatic.equals();
    }
}
```

```
public class EqualsStatic {

    public static boolean equals() {
        return false;
    }
}
```

```
@RunWith(PowerMockRunner.class)
@PrepareForTest(EqualsStatic.class)
public class SpyTest {

    private SpyObject partialMock = null;

    @Before
    public void setup() throws Exception {
        PowerMockito.mockStatic(EqualsStatic.class);
        PowerMockito.when(EqualsStatic.equals()).thenReturn(true);

        partialMock = spy(new SpyObject());
    }

    @Test
    public void testCallEquals() {
        //fail
        assertTrue(partialMock.callEquals());
    }
}


```

It occurs because in MockGateway#doMethodCall methods MockGateway#tryHandleEqualsMethod
is invoked where following statement seems triggers reals method invocation:

```
if (calledFromMockito()){
    return PROCEED;
}


```

### PR DESCRIPTION
**Pull request by Ilya-Gh**
Fix #781

### CODE REVIEW

File: tests/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github781/GitHub781Test.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    private SpyObject partialMock = null;
+    private final boolean result = true;
+
+    @Test
+    public void testCallMockStaticEquals() {
+        PowerMockito.mockStatic(EqualsStatic.class);
+        PowerMockito.when(EqualsStatic.equals()).thenReturn(result);
+        partialMock = spy(new SpyObject());
+
+        assertEquals(result, partialMock.callEquals());
```
Comment (thekingnothing) [inline tests/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github781/GitHub781Test.java]: Please, use AssertJ for assertion. We use AssertJ for all new tests. I'll add this information for contributors soon.
