### PR TITLE
Fix missing stackmap frames

### LINKED ISSUE #956: PowerMock Agent does not work EasyMock 4.x
```
samples.powermockito.junit4.agent.AnnotationUsageTest > annotationsAreEnabledWhenUsingTheJUnitRule[0] FAILED
    java.lang.VerifyError: Expecting a stackmap frame at branch target 38
    Exception Details:
      Location:
        org/easymock/EasyMockSupport.resetAll()V @16: ifeq
      Reason:
        Expected stackmap frame at this location.
      Bytecode:
        0x0000000: 2ab4 0016 b900 7201 004c 2bb9 0078 0100
        0x0000010: 9900 162b b900 7c01 00c0 0021 4d2c b900
        0x0000020: 8401 00a7 ffe7 b1           
```

Detailed description in pull request #952

### LINKED ISSUE #1005: VerifyError using the agent for Spock tests
With PowerMock 2.0.2, Spock 1.3-groovy-2.5 and JaCoCo 0.8.4,
when I apply the agent-based `PowerMockRule`, I get this verify error when trying to execute the tests:

```
Expecting a stackmap frame at branch target 50
Exception Details:
  Location:
    org/spockframework/runtime/model/ErrorInfo.$jacocoInit()[Z @4: ifnonnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 2059 c700 2e57 b200 2606 bd00 0459
    0x0000010: 0314 0027 b800 2e53 5904 122f 5359 0506
    0x0000020: b800 3453 5ab6 0038 5703 32c0 0039 59b3
    0x0000030: 0020 b0                                

java.lang.VerifyError: Expecting a stackmap frame at branch target 50
Exception Details:
  Location:
    org/spockframework/runtime/model/ErrorInfo.$jacocoInit()[Z @4: ifnonnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 2059 c700 2e57 b200 2606 bd00 0459
    0x0000010: 0314 0027 b800 2e53 5904 122f 5359 0506
    0x0000020: b800 3453 5ab6 0038 5703 32c0 0039 59b3
    0x0000030: 0020 b0                                

	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:486)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

But even if I disable JaCoCo, a verify error is thrown:
```
Expecting a stackmap frame at branch target 17
Exception Details:
  Location:
    org/spockframework/util/ExceptionUtil.throwWithSuppressed(Ljava/lang/Throwable;Ljava/lang/Throwable;)V @1: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ac6 0010 2bc6 0008 2a2b b600 302a b800
    0x0000010: 322b c600 072b b800 32b1               

java.lang.VerifyError: Expecting a stackmap frame at branch target 17
Exception Details:
  Location:
    org/spockframework/util/ExceptionUtil.throwWithSuppressed(Ljava/lang/Throwable;Ljava/lang/Throwable;)V @1: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ac6 0010 2bc6 0008 2a2b b600 302a b800
    0x0000010: 322b c600 072b b800 32b1               

	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:205)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:113)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Vampire**
When using the powermock-module-junit4-rule-agent there are `java.lang.VerifyError`s.
For example if you have some project with Spock 1.0 and use use the rule, it works just fine.
As soon as you upgrade to 1.2 or 1.3 which dropped Java 6 support, you get various of these verify errors.

They are all about "Expected stackmap frame at this location.".

I'm no Byte Buddy expert, but from what I have read, the combination of `ClassWriter.COMPUTE_MAXS` with `ClassReader.SKIP_FRAMES` is not the best idea.
`ClassReader.SKIP_FRAMES` will skip reading and visiting stack maps and stack map tables.
The JavaDoc of that attribute says it is for example useful if you use `ClassWriter.COMPUTE_FRAMES` as it recalculates the stackmap frames anyway, so there is no need to parse and visit them.
But like it is currently, they are neither parsed, nor visited, nor computed and thus they are missing when verifying.

As far as I understood there are two ways to handle this, either use `ClassWriter.COMPUTE_FRAMES` and `ClassReader.SKIP_FRAMES`,
as then the frames are not parsed or visited, but recalculated, or do not use both as they are then parsed, visited and in
the case of this visitor just copied.

As the visitor only removes the final modifiers for methods and classes now, I renamed it,
disabled even the MAXS computation and disabled the frame skipping.

From my test it seems to work better with this setting now and also all your tests are green
(except three tests that are red for me even without my changes).

Fixes #1005
Probably fixes #956, #1024, #926, #549, #558, #873, #693, #543

**Update:** also re-enabled the tests that were disabled due to this error in #952
I think the exclusion of TestNG classes in commit e948b49baa7141de7c0e824ad01ba50bb1f05484 was also due to this error and could probably be reverted.

**Work-around:** Use JVM option `-noverify` to disable the verification that complains about the missing stackmap frames.

### CODE REVIEW

**Comment by Vampire** [comment]
Hm, I don't see why the tests fail in 2 of 3 builds on Travis.
They work fine here, even if I set the environment property `powermock.byte-code-framework=Javassist` like the failing builds on Travis do. :-/

**Comment by kriegaex** [comment]
I tested this with Spock 1.3 (JUnit 4) and 2.0-M2 (JUnit 5), PowerMock with this fix works both with Mockito 2 and EasyMock tests.

Thus, I support this PR being accepted and a maintenance release being published ASAP. This was a long-standing problem which now seems to be solved and with it several related problems.

File: powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java [hunk 1]
```diff
@@ -24,18 +24,13 @@
...
-    public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
+    public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) {
         if (loader == null || shouldIgnore(className)) {
             return null;
         }
         final ClassReader reader = new ClassReader(classfileBuffer);
-        final ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
-        reader.accept(new PowerMockClassVisitor(writer),
-                ClassReader.SKIP_FRAMES);
+        final ClassWriter writer = new ClassWriter(0);
```
Comment (thekingn0thing) [inline powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java]: Can you use constant instead "magic" number 0?

**Comment by thekingn0thing** [comment]
@Vampire thank you for the PR. I added one small comment. Please, can you address it and then I will merge it and release a new version.

**Comment by Vampire** [comment]
I happily would, if there were any.
Did you maybe not add a single commit but started a review and then didn't finish it?

**Review by thekingn0thing — CHANGES_REQUESTED** [review]

**Comment by thekingn0thing** [comment]
@Vampire Yes, you are right. I started review instead single comment. I haven't been used Github for a while. Sotty.

File: powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java (hunk 1 above)
Comment (Vampire) [reply powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java]: Sure, I added one.
Btw., did you see my message on Gitter? :-)

**Review by thekingn0thing — APPROVED** [review]

File: powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java (hunk 1 above)
Comment (thekingn0thing) [reply powermock-modules/powermock-module-javaagent/src/main/java/org/powermock/modules/agent/DefinalizingClassTransformer.java]: Thanks! 
Nope, I didn't see. I haven't used Gitter for ages.

**Comment by EDGARDO-NRMA** [comment]
Should I ran this in android test?
